defmodule Blastek.Storage.Local do
  @moduledoc """
  Filesystem storage under `priv/uploads`, served by the endpoint at `/uploads`.

  The default adapter, and the one the test suite exercises: CI has no object
  store, so without a local implementation the upload path would ship untested.

  "Presigning" here is a `Phoenix.Token` bound to the key *and* the content type,
  pointing at `PUT /api/uploads`. The token carries its own expiry, and because
  the key is inside the signed payload a client cannot redirect its upload to
  someone else's key.
  """
  @behaviour Blastek.Storage

  require Logger

  @salt "storage-upload"

  @impl true
  def put(key, body, _content_type) do
    path = path_for(key)

    with :ok <- File.mkdir_p(Path.dirname(path)),
         :ok <- File.write(path, body) do
      :ok
    else
      {:error, reason} ->
        Logger.error("local storage write failed for #{key}: #{inspect(reason)}")
        {:error, reason}
    end
  end

  @impl true
  def get(key) do
    case File.read(path_for(key)) do
      {:ok, body} -> {:ok, body}
      {:error, reason} -> {:error, reason}
    end
  end

  @impl true
  def delete(key) do
    case File.rm(path_for(key)) do
      :ok -> :ok
      # Already gone is the desired end state, not a failure.
      {:error, :enoent} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  @impl true
  def public_url(key), do: "#{base_url()}/uploads/#{key}"

  @impl true
  def presign_put(key, content_type, expires_in) do
    token =
      Phoenix.Token.sign(
        BlastekWeb.Endpoint,
        @salt,
        %{key: key, content_type: content_type},
        max_age: expires_in
      )

    {:ok,
     %{
       url: "#{base_url()}/api/uploads?token=#{token}",
       # The PUT must declare the same type that was signed.
       headers: %{"content-type" => content_type}
     }}
  end

  @doc """
  Verifies an upload token, returning the key and content type it authorizes.

  Used by `BlastekWeb.UploadController`; the caller must still check that the
  request's own content type matches.
  """
  def verify_upload_token(token, expires_in \\ 900) do
    case Phoenix.Token.verify(BlastekWeb.Endpoint, @salt, token, max_age: expires_in) do
      {:ok, %{key: key, content_type: content_type}} ->
        if safe_key?(key),
          do: {:ok, %{key: key, content_type: content_type}},
          else: {:error, :invalid}

      _ ->
        {:error, :invalid}
    end
  end

  @doc "Absolute path of the storage root, created on demand."
  def root do
    Application.get_env(:blastek, __MODULE__, [])
    |> Keyword.get(:root, Path.join(:code.priv_dir(:blastek), "uploads"))
    |> to_string()
  end

  defp base_url do
    Application.get_env(:blastek, __MODULE__, [])
    |> Keyword.get(:base_url, "http://localhost:4000")
  end

  defp path_for(key) do
    unless safe_key?(key), do: raise(ArgumentError, "unsafe storage key: #{inspect(key)}")
    Path.join(root(), key)
  end

  # Keys are generated by `Blastek.Storage.build_key/3`, but this is the last
  # gate before a path hits the filesystem, so it does not get to assume that.
  defp safe_key?(key) do
    is_binary(key) and key != "" and not String.starts_with?(key, "/") and
      not String.contains?(key, "..") and not String.contains?(key, "\0")
  end
end
